feat: 脚手架第一版
tw93/Pake pull request #103
Opened 2022-11-21 16:24 UTC by wanghanzhen

2022-11-22 03:16 UTC, tw93 commented on README.md
> +npm install -g pake
这里是不是不对，是pake-cli吗

2022-11-22 03:18 UTC, tw93 commented on README.md
> +-   我有两只猫，一只叫汤圆，一只叫可乐，假如觉得 Pake 让你生活更美好，可以给汤圆可乐 <a href="https://miaoyan.app/cats.html?name=Pake" target="_blank">喂罐头 🥩🍤</a>。
这里这个空格，我再想是不是可以干掉，或者忽视文档格式化这个规则，这一块可以 @Tlntin 也一起看看

2022-11-22 03:18 UTC, tw93 commented on bin/README.md
> +npm install -g pake
这里名称需要确定下

2022-11-22 15:23 UTC, wanghanzhen commented on README.md
> +-   我有两只猫，一只叫汤圆，一只叫可乐，假如觉得 Pake 让你生活更美好，可以给汤圆可乐 <a href="https://miaoyan.app/cats.html?name=Pake" target="_blank">喂罐头 🥩🍤</a>。
这里我手动去掉了

2022-11-22 15:23 UTC, wanghanzhen commented on bin/README.md
> +npm install -g pake
已修改

2022-11-22 15:23 UTC, wanghanzhen commented on README.md
> +npm install -g pake
已修改

2022-11-23 00:07 UTC, pan93412 requested changes

2022-11-23 00:07 UTC, pan93412 commented on bin/options/icon.ts
> +  let iconResponse;
建議在這裡表明 `AxiosResponse | null` 的類型。

2022-11-23 00:07 UTC, pan93412 commented on bin/options/index.ts
> +    appOptions.name = await promptText('please input your application name', getDomain(url));
Prompt 用大寫通常比較好

2022-11-23 00:07 UTC, pan93412 commented on bin/utils/shell.ts
> +        reject(new Error(`${code}`));
建議另外做一個 `Error`，比如 `CommandRunFailed` 然後在裡面傳 number 的錯誤。

2022-11-23 00:07 UTC, pan93412 commented on bin/utils/tlds.ts
> +const tlds = [
TLDs 能從 npm 抓包會更好，不然感覺會成為一個久不維護的清單……

2022-11-23 00:07 UTC, pan93412 commented on package.json
> +    "typescript": "^4.8.4"
建議把 typescript 和 `@types` 移到 dependencies，然後用 `tsx` 或 `ts-node` 在使用者端編譯執行。`dist/index.js` 自己覺得不是很適合拿來追蹤 orz（主流的做法是丟 npm 的時候把 dist 丟上去，Git 則 ignore）

2022-11-23 00:07 UTC, pan93412 commented on bin/builders/MacBuilder.ts
> +      message: 'Detect you have not installed Rust, install it now?',
We detected that you have not installed Rust. Install it now?

2022-11-23 00:07 UTC, pan93412 commented on bin/builders/MacBuilder.ts
> +    tauriConf.tauri.bundle.icon = [options.icon];
用 `{...tauriConf.tauri.windows[0]}` 的語法會更 ES6

2022-11-23 00:07 UTC, pan93412 commented on bin/builders/MacBuilder.ts
> +    const code = await shellExec(`cd ${npmDirectory} && npm run build`);
🤔 感覺依賴 shell 不太好，用原生命令執行 `npm run build` 然後設定 workingDirectory 個人覺得會比較好。

2022-11-23 00:07 UTC, pan93412 commented on bin/builders/MacBuilder.ts
> +    await fs.copyFile(appPath, path.resolve(`${name}_universal.dmg`));
macOS only

2022-11-23 04:05 UTC, wanghanzhen commented on bin/helpers/rust.ts
> +}
这里后续支持Windows的时候会调整，这次仅mac

2022-11-23 04:14 UTC, wanghanzhen commented on bin/builders/MacBuilder.ts
> +    tauriConf.tauri.bundle.icon = [options.icon];
assign也是es6 这里主要是想要合并 不做赋值操作

2022-11-23 04:15 UTC, wanghanzhen commented on bin/builders/MacBuilder.ts
> +    const code = await shellExec(`cd ${npmDirectory} && npm run build`);
原生命令是指啥？

2022-11-23 04:16 UTC, wanghanzhen commented on bin/builders/MacBuilder.ts
> +    await fs.copyFile(appPath, path.resolve(`${name}_universal.dmg`));
是的 这里只有mac才会走

2022-11-23 04:18 UTC, wanghanzhen commented on bin/options/index.ts
> +    appOptions.name = await promptText('please input your application name', getDomain(url));
我看官方库的例子也都是小写开头🤣

2022-11-23 04:30 UTC, wanghanzhen commented on bin/builders/MacBuilder.ts
> +      message: 'Detect you have not installed Rust, install it now?',
可以调整一波

2022-11-23 04:33 UTC, wanghanzhen commented on package.json
> +    "typescript": "^4.8.4"
这个是不行的，还是得打包成js，别人用不一定有ts环境。
dist这个是之前 @tw93 说要有，所以没加ignore，dist/cli.js可以给加进去

2022-11-23 04:43 UTC, wanghanzhen commented on bin/utils/shell.ts
> +        reject(new Error(`${code}`));
后续可以考虑拓展error，目前这里场景较少，也只是做一个message显示，暂时不新增字段

2022-11-23 04:45 UTC, wanghanzhen commented on bin/options/icon.ts
> +  let iconResponse;
这里有隐式推断的，会显示类型，你是比较倾向于显式声明吗🤔

2022-11-23 04:52 UTC, wanghanzhen commented on bin/helpers/rust.ts
> +    console.error('install rust return code', error.message);
前面有reject error 这里不会取到undefined的

2022-11-24 14:22 UTC, wanghanzhen commented on bin/utils/tlds.ts
> +const tlds = [
这个是从npm包导出来的，主要是那个npm包提供的是个json入口，esm导入json还有点问题，先这样使用问题也不大，这个变化其他不大

2022-11-24 14:24 UTC, wanghanzhen commented on bin/builders/MacBuilder.ts
> +      message: 'Detect you have not installed Rust, install it now?',
已调整

2022-11-24 14:24 UTC, wanghanzhen commented on package.json
> +    "typescript": "^4.8.4"
dist/cli.js 已添加

2022-11-24 14:48 UTC, merged