feat: 增加透过 blob 下载文件的支持
tw93/Pake pull request #457
Opened 2023-06-06 08:58 UTC by jeasonnow

2023-06-06 09:10 UTC, jeasonnow commented
https://github.com/tw93/Pake/discussions/455
为这个 discussion 增加的实现，目前自测 zbook.lol ok

2023-06-06 10:24 UTC, pan93412 requested changes

2023-06-06 10:24 UTC, pan93412 commented on bin/builders/common.ts
> +function setSecurityConfigWithUrl(tauriConfig: any, url: string) {
`tauriConfig` 是有類型的，見 <https://tauri.app/v1/api/config/>

    import { TauriConfig } from "tauri/src/types"

2023-06-07 03:35 UTC, pan93412 approved these changes

2023-06-07 04:00 UTC, merged

2023-06-07 04:01 UTC, tw93 commented
感谢 @jeasonnow 提交这个好 PR，有兴趣加下我的电报吗？HiTw93 ，我拉你一起来给Pake后面建设

2023-06-07 05:24 UTC, jeasonnow commented
> 感谢 @jeasonnow 提交这个好 PR，有兴趣加下我的电报吗？HiTw93 ，我拉你一起来给Pake后面建设

可以的